In [13]:
import pandas as pd
import os, sys, time, random
import json
import numpy as np
import keras

feature_list = ["track_name", "artist_name", "album_name", "duration_ms"]

data = json.load(open("data/mpd/data/mpd.slice.0-999.json"))

playlists = pd.DataFrame(data["playlists"])

print(playlists.shape)
playlists.head()

(1000, 12)

,name,collaborative,pid,modified_at,num_tracks,num_albums,num_followers,tracks,num_edits,duration_ms,num_artists,description
0,Throwbacks,false,0,1493424000,52,47,1,"[{'pos': 0, 'artist_name': 'Missy Elliott', 't...",6,11532414,37,NaN
1,Awesome Playlist,false,1,1506556800,39,23,1,"[{'pos': 0, 'artist_name': 'Survivor', 'track_...",5,11656470,21,NaN
2,korean,false,2,1505692800,64,51,1,"[{'pos': 0, 'artist_name': 'Hoody', 'track_uri...",18,14039958,31,NaN
3,mat,false,3,1501027200,126,107,1,"[{'pos': 0, 'artist_name': 'Camille Saint-Saën...",4,28926058,86,NaN
4,90s,false,4,1401667200,17,16,2,"[{'pos': 0, 'artist_name': 'The Smashing Pumpk...",7,4335282,16,NaN

In [14]:
playlists["tracks"][0][0]["track_uri"]

'spotify:track:0UaMYEvWZi0ZqiDOoHU3YI'

In [15]:
lists = [[song["track_uri"] for song in playlist] for playlist in playlists["tracks"]]

len(lists[0])
lists[0][:5]

['spotify:track:0UaMYEvWZi0ZqiDOoHU3YI',
 'spotify:track:6I9VzXrHxO9rA9A5euc8Ak',
 'spotify:track:0WqIKmW4BTrj3eJFmnCKMv',
 'spotify:track:1AWQoqb9bSvzTjaLralEkT',
 'spotify:track:1lzr43nnXAijIGYnCT8M8H']

## tracks

In [16]:
# tracks = np.unique(np.concatenate([np.array([song["track_uri"] for song in playlist]) for playlist in playlists["tracks"]]))

# len(tracks)

In [17]:
track_params = ["track_uri"] + feature_list
track_df = pd.DataFrame(list(np.concatenate([ [dict(zip(track_params, [song[feature] for feature in track_params])) for song in playlist] for playlist in playlists["tracks"] ]) ))
track_df = track_df.drop_duplicates().reset_index(drop=True)
track_df.head()

,track_uri,track_name,artist_name,album_name,duration_ms
0,spotify:track:0UaMYEvWZi0ZqiDOoHU3YI,Lose Control (feat. Ciara & Fat Man Scoop),Missy Elliott,The Cookbook,226863
1,spotify:track:6I9VzXrHxO9rA9A5euc8Ak,Toxic,Britney Spears,In The Zone,198800
2,spotify:track:0WqIKmW4BTrj3eJFmnCKMv,Crazy In Love,Beyoncé,Dangerously In Love (Alben für die Ewigkeit),235933
3,spotify:track:1AWQoqb9bSvzTjaLralEkT,Rock Your Body,Justin Timberlake,Justified,267266
4,spotify:track:1lzr43nnXAijIGYnCT8M8H,It Wasn't Me,Shaggy,Hot Shot,227600

In [ ]:
states = track_df
actions = []
transitions = []
discount_factor = []

trajectories = lists

rewards = []
boltzmann = 0.75

N = 1000
K = 1000

weights = [random.random() for i in range(len(feature_list))]


for t in range(N):
    rewards[t] = [j for j in weights]


    for i in range(K):
        pass

In [36]:
def process_playlists(path):
    filenames = os.listdir(path)
    x = None
    initialised = False
    for filename in sorted(filenames):
        if filename.startswith("mpd.slice.") and filename.endswith(".json"):
            fullpath = os.sep.join((path, filename))
            
            data = json.load(open(fullpath))

            playlist = pd.DataFrame(data["playlists"])
            if initialised:
                x = pd.concat((x, playlist), axis=0)
            else:
                initialised = True
                x = playlist
    return x

In [37]:
all_playlists = process_playlists("data/mpd/data")

print(all_playlists.shape)
all_playlists.head()

(1000, 12)

,name,collaborative,pid,modified_at,num_tracks,num_albums,num_followers,tracks,num_edits,duration_ms,num_artists,description
0,Throwbacks,false,0,1493424000,52,47,1,"[{'pos': 0, 'artist_name': 'Missy Elliott', 't...",6,11532414,37,NaN
1,Awesome Playlist,false,1,1506556800,39,23,1,"[{'pos': 0, 'artist_name': 'Survivor', 'track_...",5,11656470,21,NaN
2,korean,false,2,1505692800,64,51,1,"[{'pos': 0, 'artist_name': 'Hoody', 'track_uri...",18,14039958,31,NaN
3,mat,false,3,1501027200,126,107,1,"[{'pos': 0, 'artist_name': 'Camille Saint-Saën...",4,28926058,86,NaN
4,90s,false,4,1401667200,17,16,2,"[{'pos': 0, 'artist_name': 'The Smashing Pumpk...",7,4335282,16,NaN